from typing import Protocol
from uuid import UUID

from ..entities.vest_device import VestDevice


class VestDeviceRepository(Protocol):
    async def save(self, device: VestDevice) -> None: ...
    async def find_by_id(self, device_id: UUID) -> VestDevice | None: ...
    async def find_by_mac_address(self, mac: str) -> VestDevice | None: ...
    async def find_by_user_id(self, user_id: UUID) -> VestDevice | None: ...
    async def find_by_mqtt_username(self, username: str) -> VestDevice | None: ...
    async def exists_by_mac_address(self, mac: str) -> bool: ...
