from typing import Protocol
from uuid import UUID

from ..entities.notification import Notification, NotificationType


class NotificationRepository(Protocol):
    async def save(self, notification: Notification) -> None: ...
    async def find_by_user_id(
        self, user_id: UUID, limit: int = 20, offset: int = 0
    ) -> list[Notification]: ...
    async def count_unread(self, user_id: UUID) -> int: ...
    async def mark_as_read(self, notification_id: UUID) -> None: ...
    async def mark_all_as_read(self, user_id: UUID) -> int: ...
    async def find_latest_by_type(
        self, user_id: UUID, type_: NotificationType
    ) -> Notification | None: ...
