from datetime import datetime
from typing import Protocol
from uuid import UUID

from ..entities.password_reset_token import PasswordResetToken


class PasswordResetTokenRepository(Protocol):
    async def save(self, token: PasswordResetToken) -> None: ...
    async def find_by_hash(self, token_hash: str) -> PasswordResetToken | None: ...
    async def invalidate_for_user(self, user_id: UUID) -> None: ...
    async def mark_used(self, token_id: UUID, used_at: datetime) -> None: ...
