from typing import Protocol
from uuid import UUID

from ..entities.user import User


class UserRepository(Protocol):
    async def save(self, user: User) -> None: ...
    async def find_by_id(self, user_id: UUID) -> User | None: ...
    async def find_by_email(self, email: str) -> User | None: ...
    async def exists_by_email(self, email: str) -> bool: ...
    async def find_all(
        self, limit: int = 100, offset: int = 0, active: bool | None = None
    ) -> list[User]: ...
    async def count_all(self, active: bool | None = None) -> int: ...
    async def count_active(self) -> int: ...
