from typing import Protocol


class VestCommandPublisher(Protocol):
    async def publish_recalibrate(self, mac_address: str) -> None: ...
    async def publish_restart(self, mac_address: str) -> None: ...
    async def publish_firmware_update(self, mac_address: str, version: str) -> None: ...
